### ISSUE TITLE
Reject access to disabled accounts

### ISSUE THREAD

**Issue by chaoran-chen** [icebreaker-science/backend#42]
A user, whose email address has not been confirmed, should not be able to actually log in.

**Comment by michael-kamel** [comment]
I made a mistake by not paying attention to where the account roles are saved and how they are actually used. The current implementation actually doesn't allow disabled account login since they don't have roles yet.
Here are some things to consider though

1. The part where the account is enabled, a role is saved and the account confirmation entry is deleted should all be done in a single transaction.
2. Since we already have disabled accounts alongside enabled accounts in the same table, we have to take them into consideration when doing lookups. for example, a user lookup shouldn't yield disabled accounts. In general, It can be left like this but it is a hassle to think about and implement anything related to accounts using this implementation.

I suggest we leave it like this until the next milestone, this shouldn't hinder this milestone in any way as far as I can tell.

**Comment by michael-kamel** [comment]
I just realized that the current implementation also causes some trouble since the account profile is not created when an email is not sent. For now I think it should be a better idea to just reject disabled account access by just checking if the account is disabled in the login logic and group the persistent data storage to avoid inconsistencies.
